name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -yq libgtk-3-dev libappindicator3-dev
      - name: Test
        run: |
          ./build.sh -a -v ./...

